// build.mjs — compiles src/*.jsx into a single dist/app.js
//
// The site used to load these files through Babel-standalone in the browser.
// That pulled ~3MB of compiler onto every visit and, because Babel fetches each
// script over XHR, it broke entirely when index.html was opened as a local file.
//
// These are classic scripts, not modules. Separate <script> tags share one
// top-level scope, which the sources rely on: app.jsx calls TweaksPanel from
// tweaks.jsx by bare name, and reads the components that bootscreen/minimax/
// arcade/casestudy register on `window`. So this transforms each file on its
// own (JSX -> JS, no module wrapper) and concatenates in load order, which
// reproduces that shared scope exactly. Bundling them as modules would give
// each file its own scope and break those references.

import { transform } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";

// Load order matters: data defines the content globals, app reads the component
// globals the middle four register on `window`.
const SOURCES = [
  "src/data.jsx",
  "src/tweaks.jsx",
  "src/bootscreen.jsx",
  "src/minimax.jsx",
  "src/arcade.jsx",
  "src/casestudy.jsx",
  "src/app.jsx",
];

const OUT = "dist/app.js";
const dev = process.argv.includes("--dev");

const JSX_OPTS = {
  loader: "jsx",
  jsx: "transform",   // React is a global from the CDN, so no auto-import
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  target: "es2018",
};

const parts = [];
for (const file of SOURCES) {
  const source = await readFile(file, "utf8");
  const { code, warnings } = await transform(source, { ...JSX_OPTS, sourcefile: file });
  for (const w of warnings) console.warn(`${file}: ${w.text}`);
  parts.push(`// ---- ${file} ----\n${code}`);
}

let out = parts.join("\n");

// Minify the concatenated script as a whole. Top-level names survive because
// this is a script, not a bundle -- esbuild can't prove they're unreferenced.
if (!dev) {
  const { code } = await transform(out, { minify: true, target: "es2018" });
  out = code;
}

const banner = "// Generated by build.mjs -- do not edit. Edit src/*.jsx and run `npm run build`.\n";
out = banner + out;

await mkdir("dist", { recursive: true });
await writeFile(OUT, out);

console.log(`${OUT} — ${(Buffer.byteLength(out) / 1024).toFixed(1)} KB${dev ? " (dev, unminified)" : " (minified)"}`);
